title: My coding journey blog
description: mostly Python and data - a blog by Arianit
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate-v2
  - jekyll-gist
  - jekyll-pdf
